# Generated by Django 5.2 on 2025-05-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
